# Generated by Django 6.0.4 on 2026-05-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("video_url", models.URLField(help_text="YouTube or local video URL")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_thumbnails/"
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
